package com.omni.core

const val HTTP_CODE_SUCCESS = 200
const val HTTP_CODE_NOT_MODIFIED = 304
const val HTTP_CODE_UnPROCESSABLE_ENTRY = 422
const val HTTP_CODE_NOT_FOUND = 404
const val HTTP_CODE_CONFLICT = 409
const val HTTP_CODE_INSUFFICIENT_QUALITY = 555